name: dart_rust_ffi_poc
version: 0.0.1
description: >-
  A PoC for native heap allocations in Rust
# This example isn't intended for publishing on pub.dev.
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  path: ^1.7.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
